In [1]:
import pandas as pd

In [2]:
import numpy
import scipy
import sklearn
import mlxtend

In [3]:
df = pd.read_csv("transaction_data.csv")

In [4]:
df

  Transaction Item1 Item2 Item3 Item4 Item5
0          T1     A     B     C     D     E
1          T2     A     C     D     E     F
2          T3     A     B     E   NaN   NaN
3          T4     A     C     F     G     H
4          T5     B     C     D     E     F

In [5]:
df = df.fillna('#')

In [6]:
df

  Transaction Item1 Item2 Item3 Item4 Item5
0          T1     A     B     C     D     E
1          T2     A     C     D     E     F
2          T3     A     B     E     #     #
3          T4     A     C     F     G     H
4          T5     B     C     D     E     F

In [7]:
df = df.drop('Transaction',axis=1)

In [8]:
!pip install mlxtend --q

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from mlxtend.preprocessing import TransactionEncoder

In [10]:
te = TransactionEncoder()

In [11]:
te_ary = te.fit_transform(df.values.tolist())

In [12]:
te.columns_

['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [13]:
transc_df = pd.DataFrame(
    te_ary,
    columns=te.columns_
)

In [14]:
transc_df

       #      A      B      C      D      E      F      G      H
0  False   True   True   True   True   True  False  False  False
1  False   True  False   True   True   True   True  False  False
2   True   True   True  False  False   True  False  False  False
3  False   True  False   True  False  False   True   True   True
4  False  False   True   True   True   True   True  False  False

In [15]:
transc_df = transc_df.drop('#',axis=1)

In [16]:
transc_df

       A      B      C      D      E      F      G      H
0   True   True   True   True   True  False  False  False
1   True  False   True   True   True   True  False  False
2   True   True  False  False   True  False  False  False
3   True  False   True  False  False   True   True   True
4  False   True   True   True   True   True  False  False

In [17]:
# from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth

In [18]:
# rules = apriori(transc_df,min_support=0.6,use_colnames=True) # shift+tab: method signature

In [19]:
rules = fpgrowth(transc_df,min_support=0.6,use_colnames=True) # shift+tab: method signature

In [20]:
rules

    support   itemsets
0       0.8        (E)
1       0.8        (C)
2       0.8        (A)
3       0.6        (D)
4       0.6        (B)
5       0.6        (F)
6       0.6     (C, E)
7       0.6     (C, A)
8       0.6     (A, E)
9       0.6     (C, D)
10      0.6     (E, D)
11      0.6  (C, E, D)
12      0.6     (B, E)
13      0.6     (C, F)

In [21]:
from mlxtend.frequent_patterns import association_rules

In [22]:
assoc_rules = association_rules(rules,min_threshold=0.8)

In [23]:
assoc_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(D),(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
1,(D),(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
2,"(C, E)",(D),0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.0,1.00,1.0,1.000
3,"(C, D)",(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
4,"(E, D)",(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
5,(D),"(C, E)",0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.0,1.00,1.0,1.000
6,(B),(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
7,(F),(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875